modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL = "https://github.com/manmaed/BedRockPlus/issues" #optional
[[mods]]
modId="bedrockplus"
version="${file.jarVersion}"
displayName="BedRock+"
updateJSONURL = "https://raw.githubusercontent.com/manmaed/BedRockPlus/main/update.json"
authors = "manmaed" #optional
logoFile = "bedrockplus_logo.png"
description='''Adds More Bedrock Stuff!'''
[[dependencies.bedrockplus]]
modId="forge"
mandatory=true
versionRange="[43.1.0,)"
ordering="NONE"
side="BOTH"