modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"
issueTrackerURL = "https://github.com/net.manmaed/BedRockPlus/issues" #optional
[[mods]]
modId="bedrockplus"
version="${file.jarVersion}"
displayName="BedRock+"
updateJSONURL = "https://raw.githubusercontent.com/net.manmaed/BedRockPlus/main/update.json"
authors = "manmaed" #optional
logoFile = "bedrockplus_logo.png"
description='''
Adds More Bedrock Stuff!
'''